version: "1"
services:
  - type: web
    name: frizerke-salon
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: frizerke-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASS
        value: your-app-password
      - key: ADMIN_EMAIL
        value: admin@salon.hr

databases:
  - name: frizerke-db
    databaseName: frizerke_db
    user: frizerke_user
    plan: free
